# Generated by Django 4.2.20 on 2025-04-02 16:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('segment_code', models.CharField(choices=[('A1', 'Nhân viên văn phòng, chủ doanh nghiệp (36-45 tuổi) có mức thu nhập cao'), ('A2', 'Nhân viên văn phòng, Freelancer ở Miền Bắc (25-35 tuổi)'), ('A3', 'Sinh viên, nhân viên văn phòng, freelancer (18-24 tuổi)'), ('B1', 'Người làm kinh doanh hoặc văn phòng (45+ tuổi) có thu nhập trung bình'), ('B2', 'Người làm nghề tự do hoặc nhân viên văn phòng (36-45 tuổi)'), ('B3', 'Người làm nghề tự do hoặc nhân viên văn phòng (25-35 tuổi) ở Miền Bắc'), ('C1', 'Sinh viên đi làm thêm, nhân viên mới đi làm (20-29 tuổi)'), ('C2', 'Nhân viên văn phòng, người làm việc tự do (30-45 tuổi) ở miền Bắc'), ('C3', 'Người mua để uống không có mục đích cụ thể (45+)')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('order_time', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d3_w9_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('group_code', models.CharField(choices=[('BOT', 'Bột'), ('SET', 'Set trà'), ('THO', 'Trà hoa'), ('TTC', 'Trà củ, quả sấy'), ('TMX', 'Trà mix')], max_length=3, primary_key=True, serialize=False)),
                ('group_name', models.CharField(editable=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d3_w9_app.productgroup')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d3_w9_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d3_w9_app.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
